'''
Created on 2013-4-6

@author: Xuankang
'''

import random
import string
import hmac

from hashlib import sha256


# randomly generated by make_salt(16)..
SECRET = "NGmfbFViloligaxO"
HASH_METHOD = sha256


def make_salt(length):
    src = string.letters
    return ''.join(random.choice(src) for _ in xrange(length))


def hash_username(name):
    return hmac.new(SECRET, name, HASH_METHOD).hexdigest()

def check_hashed_username(name, hashed):
    return hash_username(name) == hashed


if __name__ == '__main__':
    print SECRET
    hashed = hash_username("ANDRIY")
    print check_hashed_username("ANDRIY", hashed)
