'''
Created on 2013-4-6

@author: Xuankang
'''

import random
import string
import hmac

from hashlib import sha256


# randomly generated by make_salt(16)..
SECRET = "NGmfbFViloligaxO"
HASH_METHOD = sha256

#
# for saving pwd
#
def make_salt(length):
    src = string.letters
    return ''.join(random.choice(src) for _ in xrange(length))

def make_pwd_hash(name, pwd, salt = None):
    if salt == None:
        salt = make_salt(8)
    hashed = hmac.new(SECRET, name + pwd + salt, HASH_METHOD).hexdigest()
    return hashed + ',' + salt

def check_pwd(name, pwd, hashed):
    salt = hashed.split(',')[1]
    return make_pwd_hash(name, pwd, salt) == hashed


#
# for saving username in cookies
#
def hash_username(name):
    return hmac.new(SECRET, name, HASH_METHOD).hexdigest()

def check_hashed_username(name, hashed):
    return hash_username(name) == hashed
